### PR TITLE
PEP8 Compliance

### PR DESCRIPTION
**Pull request by giltolley**
Mostly removed unnecessary white space on blank lines, removed trailing white space, and shortened some lines that were over 80 characters using implicit string concatenation or method variable alignments. These changes were done on every file in the 'congress' subdirectory, with a few issues being left "as is" for convention or readability. Those items are detailed in the individual commits.

### CODE REVIEW

**Comment by eyeseast** [comment]
Going to close this since tests are failing. Will run it through pep8 by hand at some point.

**Comment by eyeseast** [comment]
Er, actually, let me take a closer look at this. Might be a TravisCI issue. Sorry.

**Comment by giltolley** [comment]
Alright, let me know. I couldn't find anything erroneous with the code, and my test.py function runs successfully. If we can at least narrow down what the issue is I could take another look.

Thanks!

**Comment by eyeseast** [comment]
Got it. TravisCI won't let PRs use my encrypted API key. Tests pass when I push. Maybe something to ask @dwillis about.

In the meantime, this actually looks good after all, so I'm going to merge. Thanks for this.

**Pull request merged**
