### PR TITLE
Adds recent vote end point.

### PR DESCRIPTION
**Pull request by astrowonk**
I probably shouldn't have edited the readme... oh well.

### CODE REVIEW

**Comment by eyeseast** [comment]
Thanks for the PR. I'll run the checks locally, since Travis CI won't let me share a key for testing. Can you revert the readme?

**Comment by astrowonk** [comment]
> Thanks for the PR. I'll run the checks locally, since Travis CI won't let me share a key for testing. Can you revert the readme?

I believe I reverted the Read me succesfully!

**Comment by bosonsoftball** [comment]
Are you ever going to merge these? I added a full member roster end point too.

**Comment by astrowonk** [comment]
I added another end point. Would would be wonderful if these could get merged in. Thanks!

**Comment by astrowonk** [comment]
Checking in on this PR.

**Comment by astrowonk** [comment]
Checking in again on this PR, @eyeseast

**Pull request merged**
